core/urls.py
from django.urls import path, re_path

from .views import FormSelectSithRecruitView, FormCreateRecruitView, FormSelectSithView, FormRecruitPostAnswersView,\
    FormSaveRecruitTestTrialView, FormSithSelectRecruitView, FormMakeHandShadowView, FormShowAnswersView

app_name = 'Recruit'

urlpatterns = [
    path('select_sith_or_recruit/', FormSelectSithRecruitView.as_view(), name='recruit_select_sith_or_recruit'),
    re_path(r'.*/create_recruit/', FormCreateRecruitView.as_view()),
    re_path(r'.*select_sith/', FormSelectSithView.as_view()),
    re_path(r'.*/save_recruit_get_test_trial/', FormSaveRecruitTestTrialView.as_view(),
            name='recruit_get_test_trial'),
    re_path(r'post_answers/', FormRecruitPostAnswersView.as_view(), name='recruit_post_answers'),
    re_path(r'.*/sith_select_recruit/', FormSithSelectRecruitView.as_view(), name='recruit_sith_select_recruit'),
    re_path(r'.*/make_hand_shadows/', FormMakeHandShadowView.as_view(), name='recruit_make_hand_shadows'),
    re_path(r'.*/show_recruit_answers/', FormShowAnswersView.as_view(), name='recruit_show_recruit_answers'),
]

recrut/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [

    path('core/', include('core.urls', namespace='core-polls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import pre_init


class Planet(models.Model):
    name = models.CharField(max_length=255, primary_key=True)


class Recruit(models.Model):
    name = models.CharField(max_length=255)
    age = models.PositiveSmallIntegerField()
    email = models.EmailField(primary_key=True)
    planet_habitat = models.ForeignKey(Planet, on_delete=models.CASCADE)


class Sith(models.Model):
    name = models.CharField(max_length=255)
    planet_of_learning = models.ForeignKey(Planet, on_delete=models.CASCADE)


class TestTrials(models.Model):
    orden_code = models.CharField(max_length=255, primary_key=True)


class Questions(models.Model):
    question = models.TextField()
    test_trial = models.ForeignKey(TestTrials, on_delete=models.CASCADE)


class Answers(models.Model):
    recruit = models.ManyToManyField(Recruit, related_name='answers')
    quest = models.ForeignKey(Questions, on_delete=models.CASCADE, related_name='answers')
    answer = models.BooleanField(default=False)


class DiscipleTeacher(models.Model):
    disciple = models.OneToOneField(Recruit, on_delete=models.CASCADE, related_name='teacher')
    teacher = models.ForeignKey(Sith, on_delete=models.CASCADE, related_name='disciples')

core/forms.py
from django import forms

class RecruitCreateForm(forms.Form):
    name = forms.CharField(label='Имя рекрута')
    age = forms.IntegerField(label='Возраст рекрута', min_value=1, max_value=10000)
    email = forms.EmailField(label='Email рекрута')
    planet_habitat = forms.CharField(label='Планета обитания рекрута')

core/views.py
from django.shortcuts import render
from .models import Planet, Recruit, Sith, TestTrials, Questions, Answers, DiscipleTeacher
from django.core.exceptions import ObjectDoesNotExist
from django.views import View
from .forms import RecruitCreateForm
from django.db import IntegrityError, models
from django.core.mail import send_mail
from .signals import LimitNumberRecordsError


from smtplib import SMTPException

from random import randint


class FormSelectSithRecruitView(View):

    def get(self, request):
        return render(request, 'select_sith_recruit.html', {})


class FormCreateRecruitView(View):

    def get(self, request):
        form = RecruitCreateForm()
        return render(request, 'create_recruit_form.html', {'form': form})


class FormSelectSithView(View):

    def get(self, request):

        siths = Sith.objects.annotate(count_disciples=models.Count('disciples'))
        all_siths = []
        more_than_one_siths = []
        for sith in siths.values():
            all_siths.append((sith['id'], sith['name'], sith['planet_of_learning_id'], sith['count_disciples']))
            if sith['count_disciples'] > 1:
                more_than_one_siths.append((sith['id'], sith['name'],
                                            sith['planet_of_learning_id'], sith['count_disciples']))
        context = {'siths': all_siths, 'more_than_one_siths': more_than_one_siths}
        return render(request, 'select_sith_form.html', context)


class FormSaveRecruitTestTrialView(View):
    # questions generator
    def __generate_questions(self):
        ordens = TestTrials.objects.values('orden_code')
        len_ordens = ordens.count()
        ind = randint(0, len_ordens - 1)
        orden_code = ordens[ind]['orden_code']
        ttrials = TestTrials.objects.get(orden_code=orden_code)
        query_set_questions = Questions.objects.filter(test_trial=ttrials)

        quests = []
        for q in query_set_questions.values():
            quests.append((q['id'], q['question']))
        return quests

    def post(self, request):
        form = RecruitCreateForm(request.POST)
        if form.is_valid():
            context = form.cleaned_data

            name = context['name']
            age = context['age']
            email = context['email']
            planet_habitat = context['planet_habitat']
            try:
                planet = Planet.objects.get(pk=planet_habitat)
                try:
                    recruit = Recruit.objects.get(name=name, age=age, email=email, planet_habitat=planet)
                except ObjectDoesNotExist:
                    try:
                        recruit = Recruit.objects.create(name=name, age=age, email=email, planet_habitat=planet)
                    except IntegrityError as exc:
                        return render(request, 'error.html', {'error': f'Пользователь с email: {email} уже существует!'})

                context = {'name': name, 'email': email}

                request.session['recruit_id'] = recruit.pk
                answers = Answers.objects.filter(recruit=recruit)

                if answers.count() == 0:
                    quests = self.__generate_questions()
                    context['quests'] = quests
                    request.session['questions'] = quests
                    return render(request, 'test_trial.html', context=context)
                else:
                    pairs_q_a = []
                    for question_answer in answers.values('quest__question', 'answer'):
                        pairs_q_a.append((question_answer['quest__question'], question_answer['answer']))
                    context['pairs_q_a'] = pairs_q_a
                    return render(request, 'test_trial_done.html', context=context)

            except ObjectDoesNotExist as exc:
                return render(request, 'error.html', {'error': f'Планеты {planet_habitat} нет в базе ({exc.args[0]})'})

        else:
            return render(request, 'error.html', {'error': form.errors})


class FormRecruitPostAnswersView(View):

    def post(self, request):
        recruit_id = request.session['recruit_id']
        recruit = Recruit.objects.get(pk=recruit_id)

        answers = Answers.objects.filter(recruit=recruit)
        if answers.count() == 0:
            quests = request.session['questions']

            for quest in quests:
                ans = Answers(quest=Questions.objects.get(id=quest[0]), answer=request.POST[str(quest[0])])
                ans.save()
                ans.recruit.add(recruit)
            return render(request, 'select_sith_recruit.html', {})
        else:
            pairs_q_a = []
            for question_answer in answers.values('quest__question', 'answer'):
                pairs_q_a.append((question_answer['quest__question'], question_answer['answer']))
            context = {'name': recruit.name, 'email': recruit.email}
            context['pairs_q_a'] = pairs_q_a
            return render(request, 'test_trial_done.html', context=context)


class FormSithSelectRecruitView(View):

    def post(self, request):

        sith_id = request.POST['selected_sith']
        request.session['sith_id'] = sith_id

        sith = Sith.objects.get(pk=sith_id)
        recruits = Answers.objects.filter(recruit__teacher__isnull=True,
                                          recruit__planet_habitat=sith.planet_of_learning).distinct(). \
            values('recruit__name', 'recruit__email', 'recruit__planet_habitat')

        if recruits.count() != 0:
            list_freedom_recruits = []
            for r in recruits:
                list_freedom_recruits.append((r['recruit__name'], r['recruit__email'], r['recruit__planet_habitat']))
            return render(request, 'select_sith_recruit_form.html', context={'recruits': list_freedom_recruits})
        else:
            return render(request, 'error.html', {'error': 'Нет свободных рекрутов'})


class FormMakeHandShadowView(View):
    def post(self, request):
        recruit_id = request.session['sith_selected_recruit']
        sith_id = request.session['sith_id']

        #if DiscipleTeacher.objects.filter(teacher=sith_id).count() < 3:
        try:
            recruit = Recruit.objects.get(pk=recruit_id)
            if DiscipleTeacher.objects.filter(disciple=recruit).count() == 0:
                sith = Sith.objects.get(pk=sith_id)
                DiscipleTeacher.objects.create(disciple=recruit, teacher=sith)
                try:
                    send_mail('The purpose of hand shadows', f'You are appointed by the shadow hand to {sith.name}',
                            'recruitingService@yandex.ru', recipient_list=[recruit.email], fail_silently=False)
                except SMTPException:
                    pass
                return render(request, 'select_sith_recruit.html', {})
            else:
                return render(request, 'error.html', {'error': 'Рекрут уже назначен рукой тени!'})
        except LimitNumberRecordsError:
            return render(request, 'error.html', {'error': 'У ситха уже 3 руки тени!'})


class FormShowAnswersView(View):
    def post(self, request):
        selected_recruit = request.POST['selected_recruit']
        request.session['sith_selected_recruit'] = selected_recruit
        recruit = Recruit.objects.get(pk=selected_recruit)

        answers = Answers.objects.filter(recruit=recruit)
        pairs_q_a = []
        for question_answer in answers.values('quest__question', 'answer'):
            pairs_q_a.append((question_answer['quest__question'], question_answer['answer']))
        context = {'name': recruit.name, 'email': recruit.email}
        context['pairs_q_a'] = pairs_q_a
        return render(request, 'select_recruit.html', context=context)




core/templates/create_recruit_form.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Create Recruit</title>
</head>
<body>
    <h1>Форма добавления рекрута</h1>
    <form method="post" enctype="multipart/form-data" action={% url "core-polls:recruit_get_test_trial" %}>
        {% csrf_token %}
        {{ form }}
        <input id="recruit-submit" type="submit">
    </form>
</body>
</html>

core/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
</head>
<body>
    {{ error }}
</body>
</html>

core/templates/select_recruit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test_trial_done</title>
</head>
<body>
<h1>Тестовое задание выполнено</h1>
     <form method="post" action={% url "core-polls:recruit_make_hand_shadows" %}>
        {% csrf_token %}
         <h2>
             Имя: {{ name }}
         </h2>
          <h2>
             Email: {{ email }}
         </h2>
          <p>{{ count }}</p>
         <div class="qqq">
         {% for pair in pairs_q_a %}
                 <p><b>{{ pair.0 }}</b></p>
                 <p4>Ответ: {{ pair.1 }}</p4>
         {% endfor %}
         </div>
    <input type="submit" value="Сделать рукой тени">
    </form>
</body>
</html>

core/templates/select_sith_form.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Select sith</title>
</head>
<body>
    <h1>Ситхи</h1>
    <form method="post" enctype="multipart/form-data" action={% url "core-polls:recruit_sith_select_recruit" %}>
        <h2>Все ситхи</h2>
        {% csrf_token %}
        <select name="selected_sith" size="10" required>
            {% for sith in siths %}
                <option value={{ sith.0 }}>{{ sith.1 }} с планеты {{ sith.2 }} / {{ sith.3 }} рук тени</option>
            {% endfor %}
        </select>
        <input id="select_sith"  type="submit">
    </form>
    <form method="post" enctype="multipart/form-data" action="sith_select_recruit/">
        <h2>Ситхи с более чем одной рукой тени</h2>
        {% csrf_token %}
        <select name="selected_sith" size="0" required>
            {% for sith in more_than_one_siths %}
                <option value={{ sith.0 }}>{{ sith.1 }} с планеты {{ sith.2 }} / количество рук тени: {{ sith.3 }} </option>
            {% endfor %}
        </select>
    </form>
</body>
</html>

core/templates/select_sith_recruit.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Select Sith or Recruit</title>
</head>
<body>
    <form method="get">
        {% csrf_token %}
        <h1>Выберите себя</h1>
        <button type="submit" formaction="create_recruit/">
            Рекрут
        </button>
        <button type="submit" formaction="select_sith/">
            Ситх
        </button>
    </form>
</body>
</html>

core/templates/select_sith_recruit_form.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Select sith</title>
</head>
<body>
    <h1>Свободные рекруты</h1>
    <form method="post" enctype="multipart/form-data" action={% url "core-polls:recruit_show_recruit_answers" %}>
        {% csrf_token %}
        <select name="selected_recruit" required>
            {% for recr in recruits %}
                <option value={{ recr.1 }}>{{ recr.0 }} , {{ recr.1 }} , {{ recr.2 }}</option>
            {% endfor %}
        </select>
        <input id="select_recruit"  value="Посмотреть ответы" type="submit">
    </form>
</body>
</html>

core/templates/test_trial.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Test trial</title>
</head>
<body>
    <h1>Тестовое задание</h1>
     <form name='qqq' method="post" enctype="multipart/form-data" action={% url "core-polls:recruit_post_answers" %}>
        {% csrf_token %}
         <h2>
             <p>Имя: {{ name }}</p>
         </h2>
          <h2>
              <p>Email: {{ email }}</p>
         </h2>
         {% for quest in quests %}
                 <p><b>{{ quest.1 }}</b></p>
                 <p><input name={{ quest.0 }} type="radio" value=True required> True</p>
                 <p><input name={{ quest.0 }} type="radio" value=False checked required> False</p>
         {% endfor %}
         <input id="recruit-post-answer" type="submit">
    </form>
</body>
</html>

core/templates/test_trial_done.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Test_trial_done</title>
</head>
<body>
<h1>Тестовое задание выполнено</h1>
     <form action={% url "core-polls:recruit_select_sith_or_recruit" %}>
        {% csrf_token %}
         <h2>
             Имя: {{ name }}
         </h2>
          <h2>
             Email: {{ email }}
         </h2>
          <p>{{ count }}</p>
         <div class="qqq">
         {% for pair in pairs_q_a %}
                 <p><b>{{ pair.0 }}</b></p>
                 <p4>Вы выбрали {{ pair.1 }}</p4>
         {% endfor %}
         </div>
    <input type="submit">
    </form>
</body>
</html>